all: sv cl

sv: sv.c
	gcc -o sv -I/usr/local/Cellar/libuv/1.8.0/include -I/usr/local/include sv.c /usr/local/Cellar/libuv/1.8.0/lib/libuv.a

cl: cl.c
	gcc -o cl -I/usr/local/Cellar/libuv/1.8.0/include -I/usr/local/include cl.c /usr/local/Cellar/libuv/1.8.0/lib/libuv.a
