ts0 := $(shell date "+%Y-%m-%d---%H-%M-%S")
ts1 = $(shell date "+%Y-%m-%d---%H-%M-%S")

test:
	@echo timestamp0 is $(ts0)
	@echo timestamp1 is $(ts1)

hoge:
	@echo timestamp0 is $(ts0)
	@echo timestamp1 is $(ts1)
	sleep 2

