#include <netdb.h>

int
main()
{
    struct hostent *e;

    e = gethostbyname( "localhostaksdfhakshdflkahlfkjakldflakjdfkasjdfkjadklfaskdjfalksdjflkadhfklasjdlfkasdkfjasldkfhalkfhlkasjfdlkajfdlklaksjdflkasjdlkfadklfjalksjdfhlakjsdlfjkahdlkfjaldjflakjdflkajsdhlfjahsdlfjhalsdjfhlakjsdfhlakjdflkajdlfkajshlkdfhalsdjfhalksfdlkajhdflkashdfjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjddddddddddddddddddddddddddddddddddkkkkkkkkkkkkkkkkkkkkkkkkaaaaaaaaaaaaaaaaaaaaaaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaksjdflaksjdflkasjdhljahsldjfhalsjdfhlkasdhflksahdlfjasldkfhasdjaskhfasldjhfalksjdflkasjdhfkajsdhlfksahdfjhasldfhaklsdhflkashflkashdflkjasdhlfkjasdkfjasldkjhasldhfalkshflakshdlfkashdlfkashlkfhaslfhaslkflaskhdflakshdfakjdhlfksahelruwqlrqwhldfhsaluflasudhflaskhdflasuhdfliuasdlifahsdlikuhaslkudfasldfhasljdfhasl;iuflawisefg;asiehdfaskhfaslkjdfhalskjflkasjfklasjdlfkasdhflkasjdhflkasdhflkasjdlfkjashdlkfajshdlkjfsaldkjfahslkdfhasldjfhalskhflaksjhflkasjflkasjhdlfkasjhdlfasdfjalskjdkjasdljkfasdfjasdlkfjaslkdfhalksfhlaksjfhlkasjfdlkajshdflkjasdhflkjasdlfkjasdkfjadlkfahsldfjhaslfdhalskfhlaksjhdflkajsdhflkajshdflakjsdflasdjfjddjjdjasldflkjasdlfkjaslfkjasdlkfjaslkdjfalksfhalkshdflakjdflakjdhflkajdlfkjsahdljfkasdlfkjahslfkjsalkdhfaslkfaklsjdflaksjdfkasjdflkasjdflkasjdhlkasjdhlfkajsdhlkfajshdlfkahsdlkfjaslkdfhaslkfhalksfhlaksfhlaksjfhlkasjdhflkasjfhlkasjhdlkfjsdhflkjsdhlkfjsahdlkfjsahdlkfsahdlkfjsalkfjhalsfhaslkfhlaksfhlaksjfhlkasjfhklasjfhlkasjfhlkasjfhlaksjfhlaksjfhklasjfdhlkasjhlkasjdhlfkajslfhasflaskfhlasfhlaklfasdlffffffffffffffffffffffffffffffffffffffffffffffffffffffffffjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaaaaaaaaaaaaaaaaaaaaaaaaaajjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj" );

    malloc_stats();

    return 0;
}
