[package]
name = "hoge"
version = "0.1.0"
authors = ["Kengo Nakajima <kengo.nakajima@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ws="*"