all:
#	gcc -I /usr/local/include/w3c-libwww showlink.c
	gcc `libwww-config --cflags` -static showlink.c -L/usr/local/lib -lwwwstream -lwwwxml -lxmltok -lxmlparse -lwwwinit -lwwwapp -lwwwhtml -lwwwtelnet -lwwwnews -lwwwhttp -lwwwmime -lwwwgopher -lwwwftp -lwwwfile -lwwwdir -lwwwcache -lwwwmux -lwwwtrans -lwwwcore -lwwwutils -lmd5 -ldl 


