all: create random

create: create.c
	gcc create.c -o create
random: random.c
	gcc random.c -o random

#	gcc -I/Developer/SDKs/MacOSX10.6.sdk/usr/include -L/Developer/SDKs/MacOSX10.6.sdk/usr/lib k.c -o k
#	gcc -I/Developer/SDKs/MacOSX10.6.sdk/usr/include -L/Developer/SDKs/MacOSX10.6.sdk/usr/lib j.c -o j

