[project]
name = "primes"
version = "0.1.0"
description = "A Model Context Protocol server for prime number calculations"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.3.0",
]
