a.out 	: db1.o TokenAdm.o DbAdm.o Query.o
	gcc db1.o TokenAdm.o DbAdm.o Query.o
db1.o	: db1.c
	gcc -c db1.c
TokenAdm.o	: TokenAdm.c
	gcc -c TokenAdm.c
Query.o	: Query.c
	gcc -c Query.c
DbAdm.o : DbAdm.c
	gcc -c DbAdm.c
