all: sv cl msv mcl mmcl mmbcl ucl echosv concl mincl
mincl: mincl.c
	gcc -std=c11 mincl.c -o mincl
sv: sv.c
	gcc -std=c11 sv.c -o sv
cl: cl.c
	gcc -std=c11 cl.c -o cl
msv: msv.c
	gcc -std=c11 msv.c -o msv
mcl: mcl.c
	gcc -std=c11 mcl.c -o mcl
mmcl: mmcl.c
	gcc -std=c11 mmcl.c -o mmcl
mmbcl: mmbcl.c
	gcc -std=c11 mmbcl.c -o mmbcl
ucl: ucl.c
	gcc -std=c11 ucl.c -o ucl
echosv: echosv.c
	gcc -std=c11 echosv.c -o echosv
concl: concl.c
	gcc -std=c11 concl.c -o concl
