#aho:
#	gcc -Wall -g aho.c `gtk-config --cflags` `gtk-config --libs`
#
#hoge:
#	gcc -Wall -g hoge.c `gtk-config --cflags` `gtk-config --libs`


#nasu:
#	gcc -Wall -g nasu.c `gtk-config --cflags` `gtk-config --libs`

u: u.c
	gcc -o u -Wall -g u.c `gtk-config --cflags` `gtk-config --libs`
