/* Generated by gen.perl 0.0 ( 1999 Apr)
 * made Sun May  9 22:42:31 1999
 * user ringo
 * host r.lan.titan.co.jp
 * src  /opt/ringo/gen/test.txt
 *
 * Protocol encoder/decoder code generator.
 * Copyright (C) 1999 Kengo Nakajima 
 *
 */
#define _test_PROTO_C_
#include "test_proto.h"


char test_mainbuf[test_BUFSIZ];
int (*test_writefunc)(int,char*,int);
int _test_i;

int test_dispatchmsg( int fd , char *recvdata , int len )
{
	char *endpoint = test_mainbuf + len;
    char *pointer = test_mainbuf;
    int shortage = 0; /* data shortage */
    int error = 0; /* Erro indicator */
	unsigned char version , command;

    if(pointer<endpoint) version = *(((char*)pointer)++); else shortage++;
    if(pointer<endpoint) command = *(((char*)pointer)++); else shortage++;
    if( version != test_VERSION ) return;

    switch( command ){
    case FUNC_test_iiii:
    {
        int a;

        if(pointer<endpoint)a_count=*(((*)pointer)++); else return -1;
if(pointer<endpoint)a=*(((int*)pointer)++); else return -1;

        return test_iiii_recv( fd ,a );
    }
    case FUNC_test_aaaa:
    {
        USERID a;

        if(pointer<endpoint)a_count=*(((*)pointer)++); else return -1;
if(pointer<endpoint)a.key=*(((unsigned int*)pointer)++); else return -1;
if(pointer<endpoint)a.user_number=*(((unsigned int*)pointer)++); else return -1;

        return test_aaaa_recv( fd ,&a );
    }
    case FUNC_test_bbbb:
    {
        USERID a;
        USERID b;

        if(pointer<endpoint)a_count=*(((*)pointer)++); else return -1;
if(pointer<endpoint)a.key=*(((unsigned int*)pointer)++); else return -1;
if(pointer<endpoint)a.user_number=*(((unsigned int*)pointer)++); else return -1;
        if(pointer<endpoint)b_count=*(((*)pointer)++); else return -1;
if(pointer<endpoint)b.key=*(((unsigned int*)pointer)++); else return -1;
if(pointer<endpoint)b.user_number=*(((unsigned int*)pointer)++); else return -1;

        return test_bbbb_recv( fd ,&a,&b );
    }
    case FUNC_test_cccc:
    {
        USERIDX x;

        if(pointer<endpoint)x_count=*(((*)pointer)++); else return -1;
if(pointer<endpoint)x.userid.key=*(((unsigned int*)pointer)++); else return -1;
if(pointer<endpoint)x.userid.user_number=*(((unsigned int*)pointer)++); else return -1;
if(pointer<endpoint)x.lang=*(((unsigned char*)pointer)++); else return -1;

        return test_cccc_recv( fd ,&x );
    }
    case FUNC_test_dddd:
    {
        unsigned char x_count;
        USERIDX x[513];

        if(pointer<endpoint)x_count=*(((unsigned char*)pointer)++); else return -1;
        for(_test_i=x_count;_test_i>=1;test_i--){
if(pointer<endpoint)x[_test_i].userid.key=*(((unsigned int*)pointer)++); else return -1;
if(pointer<endpoint)x[_test_i].userid.user_number=*(((unsigned int*)pointer)++); else return -1;
if(pointer<endpoint)x[_test_i].lang=*(((unsigned char*)pointer)++); else return -1;
        }

        return test_dddd_recv( fd ,x_count , x );
    }

		  default:
			error++;
		break;
	}
    if(shortage) return -1;
    if( error ) return -1;

    return 0;
}
int test_start( int (*writefunc)(int,char*,int))
{
	if( writefunc){
        test_writefunc = writefunc;
        return 0;
    } else {
        return -1;
    }
}
int test_end( void )
{
    return 0;
}

/* Functions for sending messages */
int test_iiii_send( int fd ,int a )

{
    char *pointer = test_mainbuf;
    char *endpoint = test_mainbuf + test_BUFSIZ - 4;
    if(pointer<endpoint)*(((char*)pointer)++) = test_VERSION;
    if(pointer<endpoint)*(((char*)pointer)++) = FUNC_test_iiii;
if(pointer<endpoint)*(((*)pointer)++)=a_count; else return -1;
if(pointer<endpoint)*(((int*)pointer)++) = htonl( a ); else return -1;

    return test_writefunc( fd , test_mainbuf , pointer - test_mainbuf );
test_send_err:
    return -1;  /* error return */
}
int test_aaaa_send( int fd ,USERID * a )

{
    char *pointer = test_mainbuf;
    char *endpoint = test_mainbuf + test_BUFSIZ - 4;
    if(pointer<endpoint)*(((char*)pointer)++) = test_VERSION;
    if(pointer<endpoint)*(((char*)pointer)++) = FUNC_test_aaaa;
if(pointer<endpoint)*(((*)pointer)++)=a_count; else return -1;
if(pointer<endpoint)*(((unsigned int*)pointer)++) = htonl( a->key ); else return -1;
if(pointer<endpoint)*(((unsigned int*)pointer)++) = htonl( a->user_number ); else return -1;

    return test_writefunc( fd , test_mainbuf , pointer - test_mainbuf );
test_send_err:
    return -1;  /* error return */
}
int test_bbbb_send( int fd ,USERID * a,USERID * b )

{
    char *pointer = test_mainbuf;
    char *endpoint = test_mainbuf + test_BUFSIZ - 4;
    if(pointer<endpoint)*(((char*)pointer)++) = test_VERSION;
    if(pointer<endpoint)*(((char*)pointer)++) = FUNC_test_bbbb;
if(pointer<endpoint)*(((*)pointer)++)=a_count; else return -1;
if(pointer<endpoint)*(((unsigned int*)pointer)++) = htonl( a->key ); else return -1;
if(pointer<endpoint)*(((unsigned int*)pointer)++) = htonl( a->user_number ); else return -1;
if(pointer<endpoint)*(((*)pointer)++)=b_count; else return -1;
if(pointer<endpoint)*(((unsigned int*)pointer)++) = htonl( b->key ); else return -1;
if(pointer<endpoint)*(((unsigned int*)pointer)++) = htonl( b->user_number ); else return -1;

    return test_writefunc( fd , test_mainbuf , pointer - test_mainbuf );
test_send_err:
    return -1;  /* error return */
}
int test_cccc_send( int fd ,USERIDX * x )

{
    char *pointer = test_mainbuf;
    char *endpoint = test_mainbuf + test_BUFSIZ - 4;
    if(pointer<endpoint)*(((char*)pointer)++) = test_VERSION;
    if(pointer<endpoint)*(((char*)pointer)++) = FUNC_test_cccc;
if(pointer<endpoint)*(((*)pointer)++)=x_count; else return -1;
if(pointer<endpoint)*(((unsigned int*)pointer)++) = htonl( x->userid.key ); else return -1;
if(pointer<endpoint)*(((unsigned int*)pointer)++) = htonl( x->userid.user_number ); else return -1;
if(pointer<endpoint)*(((unsigned char*)pointer)++) = ( x->lang ); else return -1;

    return test_writefunc( fd , test_mainbuf , pointer - test_mainbuf );
test_send_err:
    return -1;  /* error return */
}
int test_dddd_send( int fd ,unsigned char x_count , USERIDX * x )

{
    char *pointer = test_mainbuf;
    char *endpoint = test_mainbuf + test_BUFSIZ - 4;
    if(pointer<endpoint)*(((char*)pointer)++) = test_VERSION;
    if(pointer<endpoint)*(((char*)pointer)++) = FUNC_test_dddd;
if(pointer<endpoint)*(((unsigned char*)pointer)++)=x_count; else return -1;
for(_test_i=x_count;_test_i>=1;_test_i--){
if(pointer<endpoint)*(((unsigned int*)pointer)++) = htonl( x->userid.key ); else return -1;
if(pointer<endpoint)*(((unsigned int*)pointer)++) = htonl( x->userid.user_number ); else return -1;
if(pointer<endpoint)*(((unsigned char*)pointer)++) = ( x->lang ); else return -1;
        }

    return test_writefunc( fd , test_mainbuf , pointer - test_mainbuf );
test_send_err:
    return -1;  /* error return */
}

	
