
DATE=$(shell date "+%Y%m%d%H%M")


X=AAA-$(DATE)
all:
	echo $(X)
	sleep 2
	echo $(X)
	sleep 10
	echo $(X)

	sleep 10
	echo $(X)

	sleep 10
	echo $(X)

	sleep 10
	echo $(X)

	sleep 10
	echo $(X)

	sleep 10
	echo $(X)

	sleep 10
	echo $(X)

	sleep 10
	echo $(X)

	sleep 10
	echo $(X)

