a.out: hoge.c
	clang -I /usr/local/Cellar/sdl2/2.0.10/include/SDL2 hoge.c /usr/local/Cellar/sdl2/2.0.10/lib/libSDL2.a -framework CoreAudio -framework AudioToolbox -framework CoreFoundation -framework CoreGraphics -framework CoreVideo -framework ForceFeedback -framework IOKit -framework Carbon -framework Cocoa -liconv -framework Metal


