/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tdlr */

#ifndef _Included_tdlr
#define _Included_tdlr
#ifdef __cplusplus
extern "C" {
#endif
#undef tdlr_FOCUS_TRAVERSABLE_UNKNOWN
#define tdlr_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef tdlr_FOCUS_TRAVERSABLE_DEFAULT
#define tdlr_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef tdlr_FOCUS_TRAVERSABLE_SET
#define tdlr_FOCUS_TRAVERSABLE_SET 2L
/* Inaccessible static: focusTraversalKeyPropertyNames */
/* Inaccessible static: LOCK */
/* Inaccessible static: dbg */
/* Inaccessible static: isInc */
/* Inaccessible static: incRate */
#undef tdlr_TOP_ALIGNMENT
#define tdlr_TOP_ALIGNMENT 0.0f
#undef tdlr_CENTER_ALIGNMENT
#define tdlr_CENTER_ALIGNMENT 0.5f
#undef tdlr_BOTTOM_ALIGNMENT
#define tdlr_BOTTOM_ALIGNMENT 1.0f
#undef tdlr_LEFT_ALIGNMENT
#define tdlr_LEFT_ALIGNMENT 0.0f
#undef tdlr_RIGHT_ALIGNMENT
#define tdlr_RIGHT_ALIGNMENT 1.0f
#undef tdlr_serialVersionUID
#define tdlr_serialVersionUID -7644114512714619750LL
/* Inaccessible static: metrics */
/* Inaccessible static: class_00024java_00024awt_00024Component */
/* Inaccessible static: class_00024java_00024awt_00024event_00024ComponentListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024FocusListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024HierarchyListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024HierarchyBoundsListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024KeyListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024MouseListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024MouseMotionListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024MouseWheelListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024InputMethodListener */
/* Inaccessible static: class_00024java_00024beans_00024PropertyChangeListener */
#undef tdlr_serialVersionUID
#define tdlr_serialVersionUID 4613797578919906343LL
/* Inaccessible static: dbg */
#undef tdlr_INCLUDE_SELF
#define tdlr_INCLUDE_SELF 1L
#undef tdlr_SEARCH_HEAVYWEIGHTS
#define tdlr_SEARCH_HEAVYWEIGHTS 1L
/* Inaccessible static: class_00024java_00024awt_00024Container */
/* Inaccessible static: class_00024java_00024awt_00024event_00024ContainerListener */
/* Inaccessible static: nameCounter */
#undef tdlr_serialVersionUID
#define tdlr_serialVersionUID -2728009084054400034LL
#undef tdlr_serialVersionUID
#define tdlr_serialVersionUID -5836846270535785031LL
#ifdef __cplusplus
}
#endif
#endif
